# Generated by Django 5.2.2 on 2025-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date'], 'verbose_name': "Ta'lim", 'verbose_name_plural': "Ta'lim"},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Ish tajribasi', 'verbose_name_plural': 'Ish tajribalari'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': "Shaxsiy ma'lumot", 'verbose_name_plural': "Shaxsiy ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order'], 'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False, verbose_name="Hozirgi o'qish"),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=200, verbose_name="O'qish yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200, verbose_name="O'quv yurti"),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Boshlash sanasi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Hozirgi ish'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Boshlash sanasi'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilgan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub havolasi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, verbose_name='Jonli havola'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text="Vergul bilan ajratilgan texnologiyalar ro'yxati", max_length=300, verbose_name='Texnologiyalar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Dasturlash tillari'), ('framework', 'Framework va kutubxonalar'), ('database', "Ma'lumotlar bazalari"), ('tool', 'Asboblar va texnologiyalar'), ('soft', "Yumshoq ko'nikmalar")], max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome ikon sinfi', max_length=50, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(help_text="Ko'nikma darajasi 1-100 oralig'ida", verbose_name='Daraja'),
        ),
    ]
