# Generated by Django 5.2.2 on 2025-07-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tarmoq nomi')),
                ('icon', models.CharField(max_length=50, verbose_name="Ikon sinfi (masalan, 'fab fa-telegram')")),
                ('url', models.URLField(verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.personalinfo', verbose_name="Shaxsiy ma'lumot")),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order'],
            },
        ),
    ]
